In [16]:
import numpy as np

1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.


In [15]:
np_1D = np.arange(1, 21)  

total   = np.sum(np_1D)
mean    = np.mean(np_1D)
median  = np.median(np_1D)
std_dev = np.std(np_1D)
indices = np.where(np_1D > 10)[0]

print(f"Sum: {total},\nMean: {mean},\nMedian: {median},\nStd Dev: {std_dev:.2f},\nIndices > 10: {indices}")

Sum: 210,
Mean: 10.5,
Median: 10.5,
Std Dev: 5.77,
Indices > 10: [10 11 12 13 14 15 16 17 18 19]


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.  


In [ ]:
np_2D = np.arange(1, 17).reshape(4, 4)
print(np_2D)

trans = np.transpose(np_2D)
print("\nTranspose:\n", trans)

rsum = np.sum(np_2D, axis=1)   
csum = np.sum(np_2D, axis=0)    
print("\nRow sums:", rsum)
print("Column sums:", csum)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row sums: [10 26 42 58]
Column sums: [28 32 36 40]


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  


In [46]:
import numpy as np

np_3D1 = np.random.randint(1, 10, size=(3, 3))
np_3D2 = np.random.randint(1, 10, size=(3, 3))

print("Matrix 1:\n", np_3D1)
print("Matrix 2:\n", np_3D2)


sum_array = np_3D1 + np_3D2
sub_array = np_3D1 - np_3D2
multi_array = np.multiply(np_3D1,np_3D2)  

print("\nElement-wise Add:\n", sum_array)
print("\nElement-wise Sub:\n", sub_array)
print("\nElement-wise Multi:\n", multi_array)

dot_array = np.dot(np_3D1,np_3D2)
print("\nElement-wise dot:\n", dot_array)



Matrix 1:
 [[3 1 2]
 [5 8 4]
 [3 4 6]]
Matrix 2:
 [[4 3 1]
 [2 6 2]
 [8 9 8]]

Element-wise Add:
 [[ 7  4  3]
 [ 7 14  6]
 [11 13 14]]

Element-wise Sub:
 [[-1 -2  1]
 [ 3  2  2]
 [-5 -5 -2]]

Element-wise Multi:
 [[12  3  2]
 [10 48  8]
 [24 36 48]]

Element-wise dot:
 [[30 33 21]
 [68 99 53]
 [68 87 59]]


 Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [67]:
array_3x4 = np.arange(1, 13).reshape(3, 4)
print("Original 3x4 Array:\n", array_3x4)

first_two_rows = array_3x4[:2, :]
print("\nFirst 2 rows (all columns):\n", first_two_rows)

last_two_columns = array_3x4[:, 2:4]
print("\nAll rows, last 2 columns:\n", last_two_columns)



Original 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First 2 rows (all columns):
 [[1 2 3 4]
 [5 6 7 8]]

All rows, last 2 columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
